trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  azureSubscription: '64a76ca7-6de2-4427-9e55-12e3b2cdcbc5'  # Substitua pelo nome correto da sua conexão de serviço
  appName: 'task-appservice'  # Nome do seu Azure App Service
  imageName: '$(Build.SourcesDirectory)/Dockerfile'  # Caminho para o seu Dockerfile

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2  # Corrigido para a versão 2 do task AzureWebAppContainer
      displayName: Deploy Docker container to Azure App Service
      inputs:
        azureSubscription: $(azureSubscription)  # Nome da conexão de serviço
        appName: $(appName)  # Nome do seu App Service
        imageName: $(tag)  # Nome da imagem que foi construída
        isMultiContainer: false  # Se for um container único, defina como false

