version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: src/app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./src:/app/src
    restart: always
